model:
  embedding_size: 768
  time_embeddings_size: 32
  type_vocab_size: 9
  max_seq_length: 512
  depth: 5
  num_heads: 8
  intermediate_size: 3072
  learning_rate: 5.e-5
  eta_min: 1.e-8
  num_iterations: 10
  increase_factor: 2
  dropout_prob: 0.1
  use_adamw: True
model_finetune:
  num_labels: 2
  hidden_size: 768
  classifier_dropout: 0.1
  hidden_dropout_prob: 0.1
  learning_rate: 5.e-6
  eta_min: 1.e-8
  num_iterations: 10
  increase_factor: 2
  use_adamw: True
train:
  batch_size: 32
  num_workers: 4
  gpus: 1
  max_epochs: 30
  acc: 1
  mask_prob: 0.15
  persistent_workers: True
  pin_memory: True
finetune:
  batch_size: 32
  num_workers: 4
  gpus: 1
  max_epochs: 5
  acc: 1
  patience: 2
  persistent_workers: True
  pin_memory: True
